# Generated by Django 2.2 on 2019-04-20 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='project_manager',
            field=models.ManyToManyField(help_text='Has complete assessment control, including the ability to add team members, make public, or delete an assessment. You can add multiple project-managers.', related_name='assessment_pms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Can view the assessment even if the assessment is not public, but cannot add or change content. You can add multiple reviewers.', related_name='assessment_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text='Can view and edit assessment components, if project is editable. You can add multiple team-members', related_name='assessment_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='strain',
            unique_together={('species', 'name')},
        ),
    ]
