# Generated by Django 2.1.2 on 2018-11-02 02:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0002_auto_20181101_2154'),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('BMDS231', 'BMDS v2.3.1'), ('BMDS240', 'BMDS v2.4.0'), ('BMDS260', 'BMDS v2.6.0'), ('BMDS2601', 'BMDS v2.6.0.1'), ('BMDS270', 'BMDS v2.7.0')], default='BMDS270', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmd_settings', to='assessment.Assessment')),
            ],
            options={
                'verbose_name_plural': 'BMD assessment settings',
            },
        ),
        migrations.CreateModel(
            name='LogicField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(editable=False, max_length=30)),
                ('description', models.TextField(editable=False)),
                ('failure_bin', models.PositiveSmallIntegerField(choices=[(0, 'Warning (no change)'), (1, 'Questionable'), (2, 'Not Viable')], help_text='If the test fails, select the model-bin should the model be placed into.')),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, help_text='If a threshold is required for the test, threshold can be specified to non-default.', max_digits=5, null=True)),
                ('continuous_on', models.BooleanField(default=True, verbose_name='Continuous Datasets')),
                ('dichotomous_on', models.BooleanField(default=True, verbose_name='Dichotomous Datasets')),
                ('cancer_dichotomous_on', models.BooleanField(default=True, verbose_name='Cancer Dichotomous Datasets')),
                ('assessment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bmd_logic_fields', to='assessment.Assessment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveSmallIntegerField()),
                ('bmr_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=25)),
                ('overrides', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_executed', models.DateTimeField(null=True)),
                ('execution_error', models.BooleanField(default=False)),
                ('dfile', models.TextField(blank=True)),
                ('outfile', models.TextField(blank=True)),
                ('output', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('plot', models.ImageField(blank=True, upload_to='bmds_plot')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('model_id', 'bmr_id'),
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='SelectedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmd_model', to='animal.Endpoint')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmd.Model')),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('BMDS231', 'BMDS v2.3.1'), ('BMDS240', 'BMDS v2.4.0'), ('BMDS260', 'BMDS v2.6.0'), ('BMDS2601', 'BMDS v2.6.0.1'), ('BMDS270', 'BMDS v2.7.0')], max_length=10)),
                ('bmrs', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('date_executed', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dose_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmd_sessions', to='assessment.DoseUnits')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmd_sessions', to='animal.Endpoint')),
            ],
            options={
                'ordering': ('-last_updated',),
                'get_latest_by': 'last_updated',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='bmd.Session'),
        ),
    ]
