# Generated by Django 2.1.2 on 2018-11-02 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='study-attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lit.Reference')),
                ('bioassay', models.BooleanField(default=False, help_text='Study contains animal bioassay data', verbose_name='Animal bioassay')),
                ('epi', models.BooleanField(default=False, help_text='Study contains epidemiology data', verbose_name='Epidemiology')),
                ('epi_meta', models.BooleanField(default=False, help_text='Study contains epidemiology meta-analysis/pooled analysis data', verbose_name='Epidemiology meta-analysis')),
                ('in_vitro', models.BooleanField(default=False, help_text='Study contains in-vitro data')),
                ('short_citation', models.CharField(help_text='How the study should be identified (i.e. Smith et al. (2012), etc.)', max_length=256)),
                ('full_citation', models.TextField(help_text='Complete study citation, in desired format.')),
                ('coi_reported', models.PositiveSmallIntegerField(choices=[(0, 'Authors report they have no COI'), (1, 'Authors disclosed COI'), (2, 'Unknown'), (3, 'Not reported')], default=0, help_text='Was a conflict of interest reported by the study authors?', verbose_name='COI reported')),
                ('coi_details', models.TextField(blank=True, help_text='Details related to potential or disclosed conflict(s) of interest', verbose_name='COI details')),
                ('funding_source', models.TextField(blank=True)),
                ('study_identifier', models.CharField(blank=True, help_text='Reference descriptor for assessment-tracking purposes (for example, "{Author, year, #EndNoteNumber}")', max_length=128, verbose_name='Internal study identifier')),
                ('contact_author', models.BooleanField(default=False, help_text='Was the author contacted for clarification of methods or results?')),
                ('ask_author', models.TextField(blank=True, help_text='Details on correspondence between data-extractor and author, if needed.', verbose_name='Correspondence details')),
                ('published', models.BooleanField(default=False, help_text='If True, this study, risk of bias, and extraction details may be visible to reviewers and/or the general public (if assessment-permissions allow this level of visibility). Team-members and project-management can view both published and unpublished studies.')),
                ('summary', models.TextField(blank=True, help_text='Study summary or details on data-extraction needs.', verbose_name='Summary and/or extraction comments')),
            ],
            options={
                'verbose_name_plural': 'Studies',
                'ordering': ('short_citation',),
            },
            bases=('lit.reference',),
        ),
        migrations.AddField(
            model_name='attachment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='study.Study'),
        ),
    ]
