# Generated by Django 2.1.2 on 2018-11-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'preparation'), (20, 'extraction'), (30, 'qa/qc'), (40, 'rob completed')])),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'not started'), (20, 'started'), (30, 'completed'), (40, 'abandoned')], default=10)),
                ('open', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('study', 'type'),
            },
        ),
    ]
