# Generated by Django 2.1.2 on 2018-11-02 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskOfBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(db_index=True, default=False)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskofbiases', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskofbiases', to='study.Study')),
            ],
            options={
                'verbose_name_plural': 'Risk of Biases',
                'ordering': ('final',),
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_reviewers', models.PositiveSmallIntegerField(default=1)),
                ('help_text', models.TextField(default='<p>When a study is entered into the HAWC database for use in an assessment, risk of bias metrics can be entered for a metric of bias for each study. Risk of Bias metrics are organized by domain. The following questions are required for evaluation for this assessment.</p>', help_text='Detailed instructions for completing risk of bias assessments.')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rob_settings', to='assessment.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='RiskOfBiasDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rob_domains', to='assessment.Assessment')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, help_text='HTML text describing scoring of this field.')),
                ('required_animal', models.BooleanField(default=True, help_text='Is this metric required for animal bioassay studies?<br/><b>CAUTION:</b> Removing requirement will destroy all bioassay responses previously entered for this metric.', verbose_name='Required for bioassay?')),
                ('required_epi', models.BooleanField(default=True, help_text='Is this metric required for human epidemiological studies?<br/><b>CAUTION:</b> Removing requirement will destroy all epi responses previously entered for this metric.', verbose_name='Required for epidemiology?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='riskofbias.RiskOfBiasDomain')),
            ],
            options={
                'ordering': ('domain', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(10, 'Not reported'), (1, 'Definitely high risk of bias'), (2, 'Probably high risk of bias'), (3, 'Probably low risk of bias'), (4, 'Definitely low risk of bias'), (0, 'Not applicable')], default=10)),
                ('notes', models.TextField(blank=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='riskofbias.RiskOfBiasMetric')),
                ('riskofbias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='riskofbias.RiskOfBias')),
            ],
            options={
                'ordering': ('metric', 'id'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='riskofbiasdomain',
            unique_together={('assessment', 'name')},
        ),
    ]
