# Generated by Django 2.2 on 2019-04-20 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import riskofbias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskOfBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(db_index=True, default=False)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskofbiases', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskofbiases', to='study.Study')),
            ],
            options={
                'verbose_name_plural': 'Risk of Biases',
                'ordering': ('final',),
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_overall_confidence', models.BooleanField(default=False, help_text='Is this domain for overall confidence?', verbose_name='Overall confidence?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rob_domains', to='assessment.Assessment')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('assessment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, help_text='HTML text describing scoring of this field.')),
                ('required_animal', models.BooleanField(default=True, help_text='Is this metric required for animal bioassay studies?<br/><b>CAUTION:</b> Removing requirement will destroy all bioassay responses previously entered for this metric.', verbose_name='Required for bioassay?')),
                ('required_epi', models.BooleanField(default=True, help_text='Is this metric required for human epidemiological studies?<br/><b>CAUTION:</b> Removing requirement will destroy all epi responses previously entered for this metric.', verbose_name='Required for epidemiology?')),
                ('required_invitro', models.BooleanField(default=True, help_text='Is this metric required for in-vitro studies?<br/><b>CAUTION:</b> Removing requirement will destroy all in-vitro responses previously entered for this metric.', verbose_name='Required for in-vitro?')),
                ('hide_description', models.BooleanField(default=False, help_text='Hide the description on reports?', verbose_name='Hide description?')),
                ('use_short_name', models.BooleanField(default=False, help_text='Use the short name in visualizations?', verbose_name='Use the short name?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='riskofbias.RiskOfBiasDomain')),
            ],
            options={
                'ordering': ('domain', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 'Not applicable'), (2, 'Not reported'), (14, 'Definitely high risk of bias'), (15, 'Probably high risk of bias'), (16, 'Probably low risk of bias'), (17, 'Definitely low risk of bias'), (24, 'Critically deficient'), (25, 'Deficient'), (26, 'Adequate'), (27, 'Good')], default=10)),
                ('notes', models.TextField(blank=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='riskofbias.RiskOfBiasMetric')),
                ('riskofbias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='riskofbias.RiskOfBias')),
            ],
            options={
                'ordering': ('metric', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RiskOfBiasAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_reviewers', models.PositiveSmallIntegerField(default=1)),
                ('help_text', models.TextField(default='Instructions for reviewers completing assessments', help_text='Detailed instructions for completing risk of bias assessments.')),
                ('default_questions', models.PositiveSmallIntegerField(choices=[(1, 'OHAT'), (2, 'EPA')], default=riskofbias.models.RiskOfBiasAssessment.get_default_default_questions, help_text='If no questions exist, which default questions should be used? If questions already exist, changing this will have no impact.', verbose_name='Default questions')),
                ('responses', models.PositiveSmallIntegerField(choices=[(0, 'OHAT'), (1, 'EPA')], default=riskofbias.models.RiskOfBiasAssessment.get_default_responses, help_text='Why responses should be used to answering questions:', verbose_name='Question responses')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rob_settings', to='assessment.Assessment')),
            ],
        ),
    ]
